feature: Ability to silence alerts
gimlet-io/gimlet pull request #769
Opened 2023-12-15 13:41 UTC by dzsak

2023-12-15 13:42 UTC, dzsak commented
<img width="797" alt="Screenshot 2023-12-15 at 14 38 49" src="https://github.com/gimlet-io/gimlet/assets/86593861/f5a0bf7f-9060-47d5-b4e8-253581ef0543">
<img width="803" alt="Screenshot 2023-12-15 at 14 38 56" src="https://github.com/gimlet-io/gimlet/assets/86593861/afa05563-908a-41c7-bb9d-82ac8f133352">

2023-12-15 14:46 UTC, laszlocph requested changes

2023-12-15 14:46 UTC, laszlocph commented on pkg/dashboard/notifications/message.go
> +	Silenced() bool
This belongs to the alert not the message.

2023-12-15 14:47 UTC, laszlocph commented
Please also show on the alert if it is silenced. Instead of the button, show a text: "Silenced until: xxx"

2023-12-18 09:33 UTC, laszlocph requested changes
Looks, good, just minor naming and semantics.

2023-12-18 09:33 UTC, laszlocph commented on pkg/dashboard/alert/alertStateManager.go
> +			if a.alertsSilenced(nonResolvedAlert.DeploymentName, nonResolvedAlert.Type) {
This logically should be `if !a.alertsSilenced`

2023-12-18 09:33 UTC, laszlocph commented on pkg/dashboard/notifications/alertMessage.go
> +								Text: "Silence",
There should be both a `View` and a `Silence` buttons.

2023-12-18 09:33 UTC, laszlocph commented on pkg/dashboard/server/router.go
> +		r.Post("/api/silenceAlerts", silenceAlerts)
Should be `/api/silenceAlert`, since we silence a single alert at a time.

2023-12-18 13:02 UTC, dzsak commented
<img width="1167" alt="Screenshot 2023-12-18 at 14 01 30" src="https://github.com/gimlet-io/gimlet/assets/86593861/4774b545-dda4-44d2-9292-ca93d4518ffc">

<img width="692" alt="Screenshot 2023-12-18 at 14 01 37" src="https://github.com/gimlet-io/gimlet/assets/86593861/829de838-2365-4e16-99aa-cff1920e6959">

2023-12-18 18:02 UTC, dzsak commented
<img width="734" alt="Screenshot 2023-12-18 at 19 01 02" src="https://github.com/gimlet-io/gimlet/assets/86593861/46ec2473-09fd-449a-b65d-638973f5d937">

2023-12-19 07:53 UTC, laszlocph approved these changes

2023-12-19 07:54 UTC, merged